# More on Specification and Data Issues

Also covered using [Python](http://solomonegash.com/econometrics/wooldridge_python/iexample9_py.html) and [Stata](http://www.solomonegash.com/woodridge1/iexample9.html)


```{r echo=TRUE, message=FALSE, warning=FALSE}
library(wooldridge)
library(stargazer)
library(sandwich)
library(lmtest)
library(car)
rm(list = ls())
```

## Example 9.1. Economic Model of Crime

```{r}
crime_hetr_r <- lm(narr86  ~ pcnv + avgsen + tottime + ptime86 + qemp86 + inc86 + black + hispan + 1, data=crime1)
crime_hetr <- lm(narr86  ~ pcnv + avgsen + tottime + ptime86 + qemp86 + inc86 + black + hispan + pcnvsq + pt86sq + inc86sq + 1, data=crime1)
crime_robust <- coeftest(crime_hetr, vcov = vcovHC(crime_hetr, "HC1"))

stargazer(crime_hetr_r, crime_hetr, crime_robust, column.labels=c("Hetrosc1.","Hetrosc2", "Robust"), keep.stat=c("n","rsq", "adj.rsq"), no.space=TRUE, type="text")
```

## Example 9.2. Housing Price Equation

```{r}
hprice_reg <- lm(price ~ lotsize + sqrft + bdrms, data=hprice1)
prhat2<-predict(hprice_reg)**2
prhat3<-predict(hprice_reg)**3
hprice_reg_pol <- lm(price ~ lotsize + sqrft + bdrms + prhat2 + prhat3 + 1 , data=hprice1)
stargazer(hprice_reg, hprice_reg_pol, keep.stat=c("n","rsq", "adj.rsq"), no.space=TRUE, type="text")

linearHypothesis(hprice_reg_pol, c("prhat2 = 0", "prhat3 =0"))
```

Log form
```{r}
lhprice_reg <- lm(lprice ~ llotsize + lsqrft + bdrms, data=hprice1)
lprhat2<-predict(lhprice_reg)**2
lprhat3<-predict(lhprice_reg)**3
lhprice_reg_pol <- lm(lprice ~ llotsize + lsqrft + bdrms + lprhat2 + lprhat3 + 1 , data=hprice1)
stargazer(lhprice_reg, lhprice_reg_pol, keep.stat=c("n","rsq", "adj.rsq"), no.space=TRUE, type="text")

linearHypothesis(lhprice_reg_pol, c("lprhat2 = 0", "lprhat3 =0"))
```

## Example 9.3. IQ as a Proxy for Ability
```{r}
IQA <- lm(lwage ~ educ + exper + tenure + married + south + urban + black + 1, data = wage2)
IQB <- lm(lwage ~ educ + exper + tenure + married + south + urban + black + IQ + 1, data = wage2)
IQC <- lm(lwage ~ educ + exper + tenure + married + south + urban + black + IQ + educ:IQ + 1, data = wage2)

stargazer(IQA, IQB, IQC, column.labels=c("IQA","IQB", "IQC"), keep.stat=c("n","rsq", "adj.rsq"), no.space=TRUE, type="text")

```

## Example 9.4. City Crime Rates
```{r}
crime2b <- subset(crime2, crime2$year==87)
crimeA <- lm(lcrmrte ~ unem + llawexpc + 1, data=crime2b)
crimeB <- lm(lcrmrte ~ unem + llawexpc + lcrmrt_1 + 1, data=crime2b)
stargazer(crimeA, crimeB, column.labels=c("crimeA","crimeB"), keep.stat=c("n","rsq", "adj.rsq"), no.space=TRUE, type="text")
```

## Example 9.8. R&D Intensity and Firm Size

```{r}
RD1 <-  lm(rdintens ~ sales + profmarg + 1, data=rdchem) 
RD2 <-  lm(rdintens ~ sales + profmarg + 1, data=subset(rdchem, rdchem$sales<30000))
stargazer(RD1, RD2, column.labels=c("RD1","RD2"), keep.stat=c("n","rsq", "adj.rsq"), no.space=TRUE, type="text")
```

## Example 9.9. R&D Intensity

```{r}
lRD1 <-  lm(lrd ~ lsales + profmarg + 1, data=rdchem) 
lRD2 <-  lm(lrd ~ lsales + profmarg + 1, data=subset(rdchem, rdchem$sales<30000))
stargazer(lRD1, lRD2, column.labels=c("RD1logfn","RD2logfn"), keep.stat=c("n","rsq", "adj.rsq"), no.space=TRUE, type="text")
```

## Example 9.10. State Infant Mortality Rates

```{r}
infant1 <- lm(infmort ~ lpcinc + lphysic + lpopul + 1 , data = subset(infmrt, infmrt$year==1990))
infant2 <- lm(infmort ~ lpcinc + lphysic + lpopul + 1 ,data = subset(infmrt, infmrt$year==1990 & infmrt$DC==0))
stargazer(infant1, infant2, column.labels=c("Infmort1","Infmort2"), keep.stat=c("n","rsq", "adj.rsq"), no.space=TRUE, type="text")
```

. 
